### ISSUE TITLE
Learn SDR edge service code and take over support for it

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#130]
- [ ] Learn the code for, and be able to build, `sdr` edge docker image and service definition
- [ ] Learn the code for, and be able to build, `sdr2msghub` edge docker image and service definition
- [ ] Learn the code for, and process of, training the radio station detection model

**Comment by t-fine** [comment]
With the `deploy.sh` script for the cloud-side stuff, there is a new set of `ibmcloud` commands for dealing with the new event streams plans, so I will look into this and update the script appropriately.
