### ISSUE TITLE
Add yolo/detect sample to open-horizon/examples

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#138]
Working with Glen, move the services from https://github.com/TheMosquito/detect into open-horizon/examples.

Need to add instructions to README.md, and we should consider adding a pointer to it in the KC getting started section.

**Comment by dcmartin** [comment]
There is only one `yolo` example service.  Do you also want `yolo2msgub` and if yes, do you want `hal`, `wan`, and `cpu` also?

**Comment by dcmartin** [comment]
ROFLMAO; i would like to see you try.

**Comment by t-fine** [comment]
https://github.com/MegaMosquito/detect

**Comment by t-fine** [comment]
Glen just messaged me today that he will be making "big changes" to his yolo service in the next week or so and to wait until this is merged to start looking at working this into the examples repo

**Comment by t-fine** [comment]
New new one... https://github.com/MegaMosquito/achatina

**Comment by t-fine** [comment]
My PR has been submitted for this, but Glen had some questions/concerns about the documentation so we are going to go over this once the open-vino updates Sanjeev made get worked in.

**Comment by mikehyde** [comment]
@Troy-Fine Please either close this issue (if completed or no longer relevant), or change the release to Winter 1Q2021 or Future.
