### ISSUE TITLE
Fix SDR node vulnerabilities as of 4/1/2019

### ISSUE THREAD

**Issue by varatep** [open-horizon/examples#145]
Vulnerable packages:

- extend (https://github.com/open-horizon/examples/blob/master/cloud/sdr/ui/sdr-app/client/package-lock.json)
- extend (https://github.com/open-horizon/examples/blob/master/cloud/sdr/ui/sdr-app/package-lock.json)
- lodash (https://github.com/open-horizon/examples/blob/master/cloud/sdr/data-processing/ibm-functions/actions/package-lock.json)
- lodash (https://github.com/open-horizon/examples/blob/master/cloud/sdr/ui/sdr-app/package-lock.json)
- lodash (https://github.com/open-horizon/examples/blob/master/cloud/sdr/ui/sdr-app/client/package-lock.json)
- webpack-dev-server (https://github.com/open-horizon/examples/blob/master/cloud/sdr/ui/sdr-app/client/package-lock.json)
- react-dom (https://github.com/open-horizon/examples/blob/master/cloud/sdr/ui/sdr-app/package-lock.json)
- react-dom (https://github.com/open-horizon/examples/blob/master/cloud/sdr/ui/sdr-app/client/package-lock.json)
- react-dev-utils (https://github.com/open-horizon/examples/blob/master/cloud/sdr/ui/sdr-app/client/package-lock.json)

![image](https://user-images.githubusercontent.com/3941301/55340603-e0b08c80-5459-11e9-9035-ccdb913a639d.png)

**Comment by bmpotter** [comment]
Done: https://github.com/open-horizon/examples/pull/171

**Comment by bmpotter** [comment]
Fixed
