### ISSUE TITLE
Signal strength mapper sample

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#180]
- [x] Scan for signal data of all in range WiFi networks (service.sh)
- [x] Create Docker container to run service.sh
- [ ] Create Horizon Service to run wifi scan (wifisignalscan) ...may not be possible with --net=host?
- [x] Establish communication via REST API between wifi2msghub and wifisignalscan
- [x] Create top level service (pattern) that will talk to gps and wifisignalscan
- [x] Get location from gps using REST API ("Estimated" at the moment)
- [x] Solve issue of getting scan info out over REST API
- [x] Once data is flowing to wifi2msghub, format it into json structure Jay requested
- [x] Solve issue of second curl failing to wifisignalscan
- [x] Dockerize C wifi2msghub program so I can use Kafkacat and send to an Event Stream on pi
- [x] Send data to Event Stream 
- [x] Get data into database in the IBM Cloud using IBM Functions
- [x] Store data into mysql database

**Comment by t-fine** [comment]
- [ ] Scan for signal data of all in range WiFi networks (service.sh)
- [ ] Create Docker container to run service.sh
- [ ] Create Horizon Service to run wifi scan (wifisignalscan) 
- [ ] Create top level service (pattern) that will talk to gps and wifisignalscan
- [ ] Get location from gps using REST API ("Estimated" at the moment)
