### ISSUE TITLE
Restructure new samples and move to open-horizon/examples

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#185]
- [ ] Get Final list of "approved" samples to move to open-horizon/examples (Dave Booz now says he isn't sure if he wants to support the `--net=host` option)
- [x] Get USB audio adaptor sound card to test Pooja and Lily's samples

Wifi Signal Scan sample  - Troy
- Requires `--net=host`
- Services to Restructure 
    - [x] wifisignalscan
    - [x] wifi2msghub
    - [x] gps

Offline Voice Assistant - Pooja
- Services to Restructure 
    - [x] processtext
    - [x] text2speech
    - [x] audio2text
    - [x] mqtt_broker
    - [x] voice2audio
- Tested and Registered on ICP major-peacock exchange 
- [x] Write README and service/pattern description 
- [x] PR Submitted

Smart Audio w/Edge - Lily
- Services to Restructure 
    - [x] watson_speech2text
    - [x] hotword_detection (wrote new asound.conf file to work for my usb sound card) 
    - [x] stopword_removal (rewrote service as WSGI server)
    - [x] mqtt (changed topic names to more generic names to understand where the communication is coming from and going to)
    - [x] mqtt2kafka (works on ICP)
- Added Makefile's for all of the above services
- Tested and Registered on ICP major-peacock exchange 
- [x] Write README and service/pattern description 
- [x] PR Submitted

Security Camera Sample - Sadiyah
- Services to Restructure 

Edge Gateway - Sanjeev
- Requires `--net=host`
- Services to Restructure 
    - [x] efg (Edge Fabric Gateway)
    - [ ] ble
    - [ ] mqtt_broker
    - [ ] mqtt_kafka
    - [ ] oled

Noise Compliance through Situational Awareness - James 
- Services to Restructure 

Edge Fabric Chatbot - Ivan
- Services to Restructure  

Intranet Performance Monitor - Nadim
- Requires `--net=host`
- Services to Restructure  

Switch2Msghub - Abhishek
- Requires `--net=host`
- Services to Restructure 

Network Observer - Max
- Requires `--net=host`
- Services to Restructure

**Comment by t-fine** [comment]
*Offline Voice Assistant* (processtext)

Every 60 seconds this service records a five second audio clip, converts the audio clip to text locally on the edge device, finally having the host machine execute the command and speak the output. 

Registering your edge device

To run the processtext service example on your edge node, you must register your edge node with the IBM/pattern-ibm.processtext deployment pattern. Perform the steps in the Using the Offline Voice Assistant Example Edge Service with Deployment Pattern (LINK) section of the readme file.

Additional information

The processtect example source code is also available in the Horizon GitHub repository as an example for IBM Edge Computing for Devices development. This source includes the code for all of the four services that run on the edge nodes for this example. 

These services include:

The voice2audio (LINK) service which records the five second audio clip and publishes it to the mqtt broker
The audio2text (LINK) service that takes the audio clip and converts it to text offline using pocket sphinx
The processtext (LINK) service will take the text and attempt to execute the recorded command
The text2speech (LINK) service which will play the output of the command through a speaker
Finally the mqtt_broker (LINK) which is responsible for all inter-container communication 

What to do next

For instructions on Building and Publishing Your Own Version of the Watson Speech to Text to IBM Event Streams Service (LINK) follow the steps in the processtext directory of the Open Horizon examples repository.

**Comment by t-fine** [comment]
Watson Speech to Text to IBM Event Streams Service

This service listens for the hot word "Watson," once detected it captures an audio clip that is sent to an instance of Speech to Text, optionally removing stop words, then the transcribed text is send to IBM Event Streams.

Before you begin

Ensure that your system meets the following requirements:

You installed the Horizon software on your system and set your environment variables. For more information, see Installing Horizon software.
You unregistered your edge node by using the hzn unregister command and waiting for the node to be set as unconfigured.
You installed a USB sound card and microphone (development was done with a standard headphone/microphone set) to your Raspberry Pi. 

This service requires both an instance of IBM Event Streams and IBM Speech to Text to run correctly. For instructions on how to deploy an instance of event streams see the **Host CPU load percentage** (https://www.ibm.com/support/knowledgecenter/SSFKVV_3.2.1/devices/installing/cpu_load_example.html) example. 

Ensure the necessary IBM Event Stream environment variables are set:
```
echo "$EVTSTREAMS_API_KEY, $EVTSTREAMS_BROKER_URL"
```
The Event Streams topic this sample uses is `myeventstreams` by default. Though you can use any topic by setting the following environment variable:
```
export EVTSTREAMS_TOPIC=<your-topic-name>
```

Deploying an instance of IBM Speech to Text

If an instance is currently deployed, obtain the access information and set the environment variables, or follow the steps below.

Navigate to the IBM Cloud.
Click Create resource.
Enter Speech to Text in the search box.
Select the Speech to Text tile.
Select a location, select a pricing plan, enter a service name, and click Create to provision the instance.
After provisioning is complete, click the instance and note the credentials API Key and URL and export them as the following environment variables:
```
export STT_IAM_APIKEY=<speech-to-text-api-key>
export STT_URL=<speech-to-text-url>
```
7. Go to the Getting Started section for instructions of how to test the Speech to Text service.

Registering your edge device

To run the watsons2text service example on your edge node, you must register your edge node with the IBM/pattern-ibm.watsons2text-arm deployment pattern. Perform the steps in the Perform the steps in the Using the Watson Speech to Text to IBM Event Streams Service with Deployment Pattern (LINK)section of the readme file.

Additional information

The processtect example source code is also available in the Horizon GitHub repository as an example for IBM Edge Computing for Devices development. This source includes the code for all of the four services that run on the edge nodes for this example. 

These services include:

The hotworddetect (LINK) service listens for the hot word "Watson," once detected it will record a clip of audio and publish it to the mqtt broker.
The stopwordremoval (LINK) service runs as a WSGI server that can take a JSON object such as {"text": "how are you today"} and will remove common stop words and return {"result": "how you today"}.
The mqtt2kafka (LINK) service publishes data to IBM Event Streams when it receives something on the mqtt topic it's subscribed to.
Finally the mqtt_broker (LINK) which is responsible for all inter-container communication.

What to do next

For instructions on Building and Publishing Your Own Version of the Offline Voice Assistant Edge Service (LINK) follow the steps in the watson_speech2text directory of the Open Horizon examples repository.

**Comment by Rene-Ch1** [comment]
Doc part of this issue were reviewed and approved by Troy 11/20 for 3.2.1 - https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_3.2.1/devices/installing/offline_voice_assistant.html and https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_3.2.1/devices/installing/watson_speech.html

**Comment by bmpotter** [comment]
Verified
