### ISSUE TITLE
Create a script that the exchange can run on initial startup to create the samples in the exchange

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#190]
This script will require:
- ability to run hzn commands 
- HZN_EXCHANGE_USER_AUTH credentials to be set
- cloning open-horizon/examples git repo 
- new target in Makefiles to publish service or pattern without running 'docker build'  

Uses feature https://github.com/open-horizon/anax/issues/967

Currently blocked by issue https://github.com/open-horizon/anax/issues/1084

**Comment by t-fine** [comment]
Double checked with Carl after the July refresh went out and he gave the script the all clear.
