### ISSUE TITLE
cpu2msghub logs syntax error until it can communicate with cpu and gps

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#202]
The beginning of the cpu2msghub log looks like:
```
Optional environment variables (or default values): SAMPLE_INTERVAL=2, SAMPLE_SIZE=5, PUBLISH=true, MOCK=false
Checking for required environment variables for publishing to IBM Message Hub:
  HZN_ORGANIZATION=IBM
  HZN_DEVICE_ID=bpmac
  MSGHUB_TOPIC=cpu2msghub
  MSGHUB_API_KEY=LheItOe2b6UquCt7C_hdUEuQdSI1tsOXygr03gwAwyT4
  MSGHUB_BROKER_URL=9.30.210.34:30226
Will publish to topic: cpu2msghub
Starting infinite loop to read from the cpu and gps services then publish...
jq: error (at <stdin>:1): Cannot index number with string "cpu"
 Interval 1 cpu: 
(standard_in) 2: syntax error
 Interval 2 cpu: 1
(standard_in) 1: syntax error
 Interval 3 cpu: 0.25
(standard_in) 1: syntax error
 Interval 4 cpu: 0.75
(standard_in) 1: syntax error
 Interval 5 cpu: 0.75
(standard_in) 1: syntax error
(standard_in) 1: syntax error
echo {"nodeID":"bpmac","cpu":,"gps":{"lat":42.0738,"lon":-73.9797,"alt":50.05}} | kafkacat -P -b 9.30.210.34:30226 -X api.version.request=true -X security.protocol=sasl_ssl -X sasl.mechanisms=PLAIN -X sasl.username=token -X sasl.password=LheItOe2b6UquCt7C_hdUEuQdSI1tsOXygr03gwAwyT4 -X ssl.ca.location=/tmp/es-cert.pem -t cpu2msghub
```

Also, the 1st msg sent to event streams was:
```
cpu2msghub/0/3/: {"nodeID":"bpmac","cpu":,"gps":{"lat":42.0738,"lon":-73.9797,"alt":50.05}}
```

(Note there is no value after the `"cpu"` field. This is invalid json.)

It is normal/expected that a service might not get a good result from required service api's for the 1st few tries, because all the services start concurrently, so the top-level service might start calling the required services before they have finished initializing. But in this case cpu2msghub should handle those errors more gracefully and not log syntax errors and not send invalid json to event streams.

BTW, i saw these error when running it via `hzn dev service start -S`. I think they will also happen when run via a full `hzn register ...`. But it will be easier for you to debug with `hzn dev service start -S`.

**Comment by bmpotter** [comment]
Found and fixed the problem. It was caused by the fact that sometimes for the 1st call to cpu, it will come back with a 200 http code but no data. Submitted PR https://github.com/open-horizon/examples/pull/212 to handle that case.

**Comment by t-fine** [comment]
Ran the new version of `cpu2msghub` using `hzn register` and `hzn dev service start -S` confirming there was no `(standard_in) 2: syntax error` in the logs.
