### ISSUE TITLE
Change example msghub dirs/files, and env vars to evtstreams

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#222]
- [x] env vars to `EVTSTREAMS_*`
- [x] cpu2msghub to cpu2evtstreams
- [x] dir msghub to evtstreams
- [x] ask rene to do the corresponding small changes to KC

**Comment by t-fine** [comment]
https://github.com/t-fine/examples/tree/msghub-to-evstrm/edge/evtstreams/cpu2evtstreams
