### ISSUE TITLE
Write script to automate the Gather info and files step

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#243]
- [x] Automate as many of the steps in [Gather the necessary information and files](https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_3.2.1/devices/installing/adding_devices.html#prereq-horizon) as possible.
- [x] We also might want to want to add the step of pulling down `agent-install.sh` from the anax repo and make it executable.
- [x] Also, provide the option to tar up the files, so they can more easily be transferred to edge nodes. This is also needed for the [batch node install](https://ibm.ent.box.com/notes/540559786985) process.

Not sure yet where this script should live.

**Comment by t-fine** [comment]
For now I added the script to the tools directory in the open-horizon git repo, but that was just so I could save it in GitHub. 

https://github.com/t-fine/examples/blob/gather-script/tools/edgeDeviceFiles.sh

- [ ] add flag to specify distribution (xenial or bionic) if 64-bit-ARM or x86_64-LINUX are specified

**Comment by t-fine** [comment]
Assumptions:

- cloudctl and kubectl are installed 
-  ICP_URL, USER, and PW must be set for `cloudctl login ...` command. They are checked in first function

**Comment by t-fine** [comment]
**--------------- Knowledge Center Doc Changes -------------------**

**### Gather the necessary information and files**

The script in this section only needs to be executed **once**, but must be performed on an x86 host (Linux, macOS, or Windows). If your edge device is a different architecture (for example arm or arm64), then run the script in this section on an x86 host and copy the resulting tar file to your edge device.

1. Install the IBM Cloud Private command line interface (cloudctl) and the Kubernetes command line interface (kubectl) by following the steps in Installing cloudctl.

Alternatively, you can install kubectl using your package manager. For more information about installing kubectl with your package manager, see Install and set up kubectl. 

2. After cloudctl is installed, ask your IBM Cloud Private cluster administrator for the IBM Cloud Private URL, username, and password. Export these values as environment variables:
```
export ICP_URL=<icp-url>
export USER=< username>
export PW=<password>
```

3. Download and run the latest version of the `edgeDeviceFiles.sh` script to gather the necessary files to register an edge node with the `agent-install.sh` script.

Usage: ./edgeDeviceFiles.sh <edge-device-type> [-d <distribution>] [-t] 

Supported edge device values: 32-bit-ARM , 64-bit-ARM , x86_64-LINUX , macOS 

When installing on **64-bit-ARM** or **x86_64-LINUX**: you can specify `-d xenial` instead if bionic for the older version of Ubuntu. The `-d` flag is ignored with all other <edge-device-type> values. 

Including the `-t` flag will create an `agentInstallFiles.tar.gz` file containing all gathered files.

**Comment by Rene-Ch1** [comment]
This might be related to https://github.ibm.com/Edge-Fabric/docs/issues/228

**Comment by bmpotter** [comment]
Tested/used this multiple times and it worked like a champ!
