### ISSUE TITLE
Ongoing: help users and keep adding to/correcting FAQ & Troubleshooting guide

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#244]
Monitor the `edge-fabric-users` slack channel and help users with their problems, or pull in a SME (subject matter expert) if necessary.

In the process, improve the [FAQ](https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_3.2.1/devices/getting_started/faq.html) page and the 2 pages linked from [Troubleshooting](https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_3.2.1/devices/troubleshoot/troubleshooting.html) by:
- adding sections for problems that arise more than once, or seem like they will be a common problems
- correct sections whose problem resolution is wrong or out of date
- think "how could IEC4D be improved to prevent the user from hitting this problem?" Raise ideas for improvements to the relevant people on the dev team.

**Comment by mikehyde** [comment]
@t-fine  Please either close this issue (if completed or no longer relevant), or change the release to `Winter` or `Future` Release.
