### ISSUE TITLE
Modify the structure of the cpu2evtstreams, sdr2msghub, mms (processtext & watsons2text) readmes to match the helloworld readme

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#249]
Specifically:
- [x] Create a list of links at the top to each of the sections
- [x] Use explicit anchors in the sections below:
- [x] Create a Preconditions section that accomplishes the equivalent of what the KC pages have the user do before linking over here
- [x] Break the **First-Time Edge Service Developer...** section into its own `.md` file
- [x] Break the **Process for the Horizon Development Team...** section into its own `.md` file (and don't link to it from anywhere)
- [ ] Give new links to rene to use from KC

**Comment by t-fine** [comment]
- [ ] cpu2evtstreams
- [ ] sdr2evtstreams
- [ ] mms
- [ ] watson_speech2text
- [ ] processtext
