### ISSUE TITLE
Write detailed policy page

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#251]
You already created a good [policy overview page](https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_3.2.1/devices/getting_started/policy.html) associated with the example of using helloworld with policy. That is the right level of brief info to give them so they have a little idea what they are doing in the helloworld sample.

But we also need a more in-depth policy page in KC that explains how to use most of the policy features. Use https://ibm.ent.box.com/notes/440068370992 as the source of info for this new page.

Once it is completed, it should go in the new **Common Tasks** section of our KC docs.

**Comment by t-fine** [comment]
Current "Detailed Policy Page"

https://ibm.box.com/s/3ciokz6nlnd4ghzi5mk45j1mwsl5036o

**Comment by t-fine** [comment]
More up to date version with comments addressed and policy example worked in:

https://ibm.ent.box.com/notes/571041239092

**Comment by bmpotter** [comment]
Reviewed, looks good!
