### ISSUE TITLE
MMS example removed? Will another MMS example be provided?

### ISSUE THREAD

**Issue by dianadujing** [open-horizon/examples#259]

**Comment by t-fine** [comment]
Hello, sorry for the confusion! I just finished up a new example that uses the MMS, it's called helloMMS and you can find it here:

https://github.com/open-horizon/examples/tree/master/edge/services/helloMMS

**Comment by t-fine** [comment]
@dianadujing ...not sure if this gives you a notification from a comment so I thought I'd try to tag you just in case

**Comment by dianadujing** [comment]
@t-fine Thank you, Troy!
