### ISSUE TITLE
Write customer documentation explaining the example ci/cd process

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#266]
Give a brief overview of 1 way to do ci/cd for their own edge services, and point them to the relevant scripts, makefiles, and travis script. Then give it to rene and should can add it as another link in the Further Reading section of the “Developing edge services with IBM Edge Computing for Devices” page.

**Comment by t-fine** [comment]
Documentation here:

https://ibm.box.com/s/rbdtudr7tpcjbwyih6jxs1is0utvs4dl

**Comment by bmpotter** [comment]
https://ibm.ent.box.com/notes/604085290276
