### ISSUE TITLE
Test the edge node batch install process (find gaps and document)

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#268]
Test the batch install process as outlined in the [Edge Node Batch Install design](https://ibm.ent.box.com/notes/540559786985). For now only test the SSH method. The purpose of testing is twofold:

1. See if there are any gaps in the process (steps that are missing, etc.)
1. Keep detailed notes as you test so they can be given to rene as input for the KC documentation for this feature

**Comment by t-fine** [comment]
Steps for Batch Install process:

https://ibm.box.com/s/vugd2n4p8ssm7d3jf52awwxwasyqik4k

**Comment by bmpotter** [comment]
Verified
