### ISSUE TITLE
Complete the full Developer Guide so it is ready for general use

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#28]
there is a lot of good info in the developer guide you wrote that i want to make available to users. I know it needs updating and i’ve been thinking about the best way to make use of the guide and here’s my thoughts: the dev quick start has the step-by-step, but almost nothing giving the bigger picture about how all the pieces fit together and general concepts and architecture about horizon and how it fits with wiotp. The developer guide already has a lot of this, so i suggest transforming it into a Horizon Principles and Concepts doc (title can be changed).

I don’t think it is worth it to try to have step-by-step commands in the developer guide. I don’t want us to have 2 places we have to maintain that info, and with the developer guide being longer, it will always take longer to review

in my mind that also goes for the step-by-step of setting up bluemix, wiotp ui, etc. I know we only cover that very tersely in the quick start, but i’m hoping the wiotp team can provide that info

the updates to the developer guide would also have to include converting it from microservice/workload to services. See the services design for some background info on that: https://docs.google.com/document/d/1xKCPP8Rx_KTGZxYFOl4ZEg-hE1qGO8eUAf-i_FyGzGA/edit#heading=h.sb4u7ixyrfmz

**Comment by TheMosquito** [comment]
After an intro about "what is Edge" (and why is it like this), I think this sort of tabel of contents:

**Comment by TheMosquito** [comment]
As today comes to a close I have completed the first part of the above outline.  The most interesting, and hopefully the easiest to write, portions remain:
1. How Horizon Works
  * Overview
  * Horizon Exchange
  * Horizon Switchboard
  * Horizon Agent ("anax")
  * Horizon Agreement Bot ("agbot")
1. Edge Software Design
  * Hardware architectures
  * Microservices, modularity
  * Software size
  * Software dependencies (self-contained)
  * Software configuration, customization
  * Privilege, access
  * CPU/GPU/memory consumption
  * Network bandwidth
  * Network outage-tolerant
I have not made any diagrams at all yet.  So it's just a long text file at this point.  I plan to go back and add diagrams when the text is all done.  I think the first draft can be published without the diagrams and just add them as they are created.
So far it's about 20K of text (around 3000 words).

**Comment by bmpotter** [comment]
Doc is here: https://github.com/open-horizon/examples/blob/master/edge/doc/Edge-Development-Concepts.md
