### ISSUE TITLE
Change cpu2evtstreams example to use .cfg files for env vars

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#281]
In the [cpu2evtstreams KC page](https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.0/devices/installing/cpu_load_example.html), when they are deploying an instance of Event Streams, have them put the `EVTSTREAMS_*` env vars in a file called `event-streams.cfg`. Then the [Preconditions section of the github cpu2evtstreams readme](https://github.com/open-horizon/examples/blob/master/edge/evtstreams/cpu2evtstreams/README.md#preconditions) can instruct the user to get `event-streams.cfg` from whoever deployed Event Streams (maybe themselves), copy it to the edge node, and run `eval export $(cat event-streams.cfg)`

Also in the cpu2evtstreams preconditions section, have them get the `agent-install.cfg` file and the api key that were created in the "Gather ..." section and eval the cfg file (instead of explicitly setting `HZN_ORG_ID`).

**Comment by t-fine** [comment]
New deploying steps 

8. You can either create credentials in your terminal or obtain them if they are already created. To create credentials, click Service credentials > New credentials. Create a file called `event-streams.cfg` with your new credentials formatted like the following codeblock to make sharing and exporting these environment variables easy:
```
EVTSTREAMS_API_KEY="<the value of api_key>"
EVTSTREAMS_BROKER_URL="<all kafka_brokers_sasl values in a single string, separated by commas>"
```

For example, from the view credentials pane:
```
EVTSTREAMS_BROKER_URL=broker-4-x7ztkttrm44911kc.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-3-x7ztkttrm44911kc.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-2-x7ztkttrm44911kc.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-0-x7ztkttrm44911kc.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-1-x7ztkttrm44911kc.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-5-x7ztkttrm44911kc.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093
```
9. After you have created `event-streams.cfg` set these environment variables in your shell now:
```    
eval export $(cat event-streams.cfg)
```

**Comment by Rene-Ch1** [comment]
For doc content, I made the update and Troy reviewed and approved 2.18 for the next 4.0 refresh. 

https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.0/devices/installing/cpu_load_example.html
