### ISSUE TITLE
Change exchangePublishScript.sh to publish sample business policies to the cluster org

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#286]
Since business policies can't be public, customers can't use the business policies from the IBM org, and generally can't even view them (because they don't usually have credentials in the IBM org). So change `exchangePublishScript.sh` to publish the sample business policies to the cluster org instead. You may have to add `<cluster-name>` as an argument to the script, because `exchangePublishScript.sh` may not have the right info to be able to query that, but the caller does.

I think the example business policies should have a constraint like `openhorizon.example == helloworld` (or cpu2evtstreams, etc.). That way the nodes that want to use it can just set this node policy property: `openhorizon.example: helloworld`

**Comment by t-fine** [comment]
PR I submitted for this:
https://github.com/open-horizon/examples/pull/301

**Comment by bmpotter** [comment]
A couple of small updates are needed:

- [ ] Since to have the deployment policies created, the cluster org needs to be passed as an arg, ensure the 4.1 KC documentation has them set `CLUSTER_ORG` and then uses the cmd:

```
curl https://raw.githubusercontent.com/open-horizon/examples/v4.1/tools/exchangePublishScript.sh | bash -s -- -c $CLUSTER_ORG
```

- [ ] The script requires that `EXCHANGE_ROOT_PASS` be set, but doesn't seem to actually use it. I suggest the script not require that `HZN_EXCHANGE_USER_AUTH` be set, and then set that internally to `root/root:$EXCHANGE_ROOT_PASS`
- [ ] Cloning the examples repo in the current dir is a lot of files to put there, that won't get cleaned up if the script exits with an error. Might be better to clone it in `/tmp/`
