### ISSUE TITLE
Make single-arch patterns for helloMMS in exchangePublishScript.sh

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#288]
In the [helloMMS PR](https://github.com/open-horizon/examples/pull/287) i modified `object.json` to have the `destinationType` field set to the single-arch pattern, so that in the `CreateService.md` we didn't have to make them build their docker image for all 3 arch's. But this also means that for the "Use" case (`README.md`), in order to use the same `object.json` they need to have the single-arch patterns available to them in the IBM org.

I added a helloMMS make target called `publish-only-pattern-each-arch` to create these single-arch patterns, so `exchangePublishScript.sh` needs a special-case to run that (in addition to `make publish-only`) for the `helloMMS` dir.

**Comment by t-fine** [comment]
Going to solve this by expanding the `helloMMS` makefile `publish-only` target to the following:

```
publish-only:
	ARCH=amd64 $(MAKE) publish-service-overwrite
	ARCH=arm $(MAKE) publish-service-overwrite
	ARCH=arm64 $(MAKE) publish-service-overwrite
	hzn exchange pattern publish -f horizon/pattern-all-arches.json
        $(MAKE) publish-only-pattern-each-arch 
```

**Comment by bmpotter** [comment]
I added that to PR https://github.com/open-horizon/examples/pull/287 so closing this issue
