### ISSUE TITLE
A few problems in examples (from shake)

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#293]
### Problem 1
Shake: While working on the hello world example on my mac, the mounted folder shared by docker was owned by root which required me to chown the folder manually to make thing work. The error msg occurred in step 4 of [Install the Horizon agent on your edge device and register it with the hello world example](https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.0/devices/installing/registration.html), I think when `agent-install.sh` starts the anax container.

This was the command i used to fix it was:
```
sudo chown -R Abhishek.Preman1@ibm.com /private/var/tmp/horizon
```

BP: on our macs troy and i both have /private/var/tmp/horizon owned by our id, but we are not sure if we manually did that or not. Could be a difference in macOS version. To be safe, `agent-install.sh` should change the owner of this dir like shake did above.

### Problem 2
Shake: While working on the mms example, i was having trouble running the hzn exchange service publish command. Turns out this was because the docker auth tokens were stored in macosx keychain. The box to uncheck the keychain storage option in the docker prefs was checked and disabled, so i couldn't change it that way. Therefore i had to manually edit `~/.docker/config.json` and set `"credsStore": "",`

BP: According to https://github.com/docker/for-mac/issues/3774 if you check `Include VM in Time Machine backups` then the `Securely store Docker logins in macOS keychain` will be enabled so you will be able to uncheck it, then you can uncheck `Include VM in Time Machine backups` if you want. Finally, click `Apply & Restart`

Update the instructions in step 2 of [Preparing to create an edge service](https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.0/devices/developing/service_containers.html)

 ### Problem 3
Shake: Also before trying to run the `hzn mms object publish` command in the helloMMS sample, we need to unset `HZN_FSS_CSSURL`  in case it was set in the local env.

BP: i know that, for example, the helloworld sample has you run `eval export $(cat agent-install.cfg)` which will export `HZN_FSS_CSSURL`, but it should be the same value you need in the mms sample. Shake somehow had it set to `HZN_FSS_CSSURL=http://localhost:8580`. My guess is he must have made a mistake with 1 of the mms cmds when running the service thru `hzn dev`, and got the variable set in the environment, instead of just for those cmds. I don't think there is any change for us to make to the instructions right now, just keep an eye on this.

**Comment by bmpotter** [comment]
Troy, please make the changes as described above. Thx!

**Comment by t-fine** [comment]
https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.0/devices/developing/service_containers.html

**Procedure** 

2. If you are using macOS as your development host, configure Docker to store credentials in ~/.docker:
    1. Open the Docker **Preferences** dialog
    2. Uncheck **Securely store Docker logins in macOS keychain**
        - If you can not uncheck this box follow these instructions:
            1. Check **Include VM in Time Machine backups**
            2. This should enable you to uncheck **Securely store Docker logins in macOS keychain**
            3. Uncheck **Include VM in Time Machine backups** if you want
            4. Click **Apply & Restart**

**Comment by t-fine** [comment]
- Added problem 1 to anax issue 1502 that is now assigned to me 
- sent the updated content for step 2 in the device preparation page to address problem 2 to Rene

**Comment by mikehyde** [comment]
@t-fine Please either close this issue (if completed or no longer relevant), or change the release to Winter 1Q2021 or Future.
