### ISSUE TITLE
'hzn service log' cannot be recognized

### ISSUE THREAD

**Issue by dianadujing** [open-horizon/examples#294]
command used: `hzn service log`
command output: `hzn: error: expected command but got "log", try --help`
The **version** of Horizon installed on my device:
```
Horizon CLI version: 2.23.30-v3.2.1
Horizon Agent version: 2.23.30-v3.2.1
```

**Comment by t-fine** [comment]
Hello @dianadujing I believe you're getting that error because `hzn service log` was not yet implemented with that version of horizon. Our current `4.0` release is using horizon version `2.24.18` so if you have the ability to update your environment I think that would be the best option

**Comment by dianadujing** [comment]
@t-fine Can your team help to highlight the release version on documents for each commands?

**Comment by t-fine** [comment]
@dianadujing one thing we do at the moment is with each release we create a branch at that time, so in this case it was the `v3.2.1` branch, and on that branch you would not find any commands that are not compatible with that release
