### ISSUE TITLE
FFT Service 

### ISSUE THREAD

**Issue by jsusan** [open-horizon/examples#316]
Create a FFT service and any related code, including documentation and tests, to implement this service. 
Dockerize / Horizonize an FFT service - suggest one container could stream audio to another container that would process it with FFTs, and provide result data in some easy-to-consume format (e.g., JSON) that some example application could consume? Maybe use an MQTT broker in the middle to facilitate asynchronous pub/sub? Or maybe do something more basic and place all of the above into a single container? 
We are completely flexible on this example program. The language or languages you use to develop this is not important to us. MQTT doesn't matter either. If you think it is the right tool, go for it, otherwise use whatever you think is best. Same with alsa. 

- SoftServe is currently working this issue

**Comment by vkorn** [comment]
Per email discussion: working on this issue, will submit PR when ready.

**Comment by jsusan** [comment]
Vlad update: We’re working with Glen on the PR merge, expecting finish on Friday. All communication is in PR itself
