### ISSUE TITLE
Change lower-level services to port 8080, then run non-root

### ISSUE THREAD

**Issue by t-fine** [open-horizon/examples#349]
Since the lower-level services (such as `cpu` and `gps`) bind to port 80 they require root privileges. Change them to 8080 to run as non-root user and add in any additional privileges (with `cap-add`) if necessary. 

Current method of running `helloworld` as non-root user from `Dockerfile.amd64`:
```
# Create hzngroup and hznuser
RUN addgroup -S hzngroup && adduser -S hznuser -G hzngroup

# Run container as hznuser user
USER hznuser
```

**Comment by clementkng** [comment]
Hi @t-fine, I'm interested in trying out this issue. However, I got stuck figuring out how to run the [cpu](https://github.com/open-horizon/examples/tree/master/edge/services/cpu_percent) and [gps](https://github.com/open-horizon/examples/tree/master/edge/services/gps) example services. Is there a pattern/policy I could use to `hzn register` my node so I can get a locally running version?
