### ISSUE TITLE
Operator Service Updates

### ISSUE THREAD

**Issue by t-fine** [open-horizon/examples#360]
- [x] since the creation of your own service is the same for a cluster or device point to that process early in the `CreateService.md` doc
- [x] change the name of the operator tar to `operator.tar.gz` to make it simple for users so they don't have to edit `service.definition.json`
- [x] work in an easy update around step 3 for users to make it their own
- [x] additional instruction if using OCP cluster (may need some additional investigation here)

**Comment by t-fine** [comment]
Slack conversation with user
---------------------------------------------------

He was running the cluster on OCP 4.3. The deploycheck param failed because it did not have a HZN_DEVICE_ID.. not sure why… then he needed to grant more permissions to his OCP cluster with
oc adm policy add-scc-to-user privileged -z simple-operator -n openhorizon-agent

**Comment by jiportilla** [comment]
related issue - https://github.ibm.com/Edge-Fabric/docs/issues/531

**Comment by t-fine** [comment]
Some commands I may need to update...

Create edge cluster 
```
hzn exchange node create --node-type="cluster" -u $HZN_EXCHANGE_USER_AUTH -n $HZN_EXCHANGE_NODE_AUTH
```
Confirm new node
```
hzn exchange node confirm  -u $HZN_EXCHANGE_USER_AUTH -n $HZN_EXCHANGE_NODE_AUTH
```

Add new deployment policy 
```
cat deployment.policy.json | hzn exchange deployment addpolicy -u $HZN_EXCHANGE_USER_AUTH -f- <some policy name>
```

and any others like this...

**Comment by t-fine** [comment]
make a note that this is done from a development machine not the cluster host machine
