### ISSUE TITLE
Run GPU inferencing service on cluster

### ISSUE THREAD

**Issue by t-fine** [open-horizon/examples#372]
Working partially on this today (Friday 7/17) and Monday if necessary 
- expose port

**Comment by t-fine** [comment]
- this involves running the agent on an open source kube cluster 
- need to expose port 5200 for the service

**Comment by dcmartin** [comment]
Is this proposed to be implemented in conjuction with KubeFlow?

**Comment by t-fine** [comment]
This was insertion to the work for project feijoa, which was successfully completed.
