### ISSUE TITLE
Fix DependaBot Security Alerts

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/examples#387]
DependaBot is telling us about several libraries with issues that need to be upgraded and tested ASAP:

https://github.com/open-horizon/examples/network/alerts

Please upgrade and test to confirm that nothing is broken.  As you go along, please make a note of any missing tests or potential for automation.

**Comment by clementkng** [comment]
@joewxboy the github link listed above 404s for me.

**Comment by joewxboy** [comment]
Yeah, now it is for me too! Let me poke around.

**Comment by clementkng** [comment]
In the meantime, are you simply referring to the PRs that DependaBot automatically opens in this repo? https://github.com/open-horizon/examples/search?q=dependabot&state=open&type=issues

**Comment by joewxboy** [comment]
@clementkng Yes and no.  Opening PRs is not automated ... someone has to initiate them.  When you see the list, there are approximately 10 without PRs, and none of them have been tested AFAIK, although the risk is minimal that these are breaking changes.  We should test when and where possible.  When not possible, we should note that.

**Comment by clementkng** [comment]
@t-fine closing this
