### ISSUE TITLE
Rework helloworld Go operator example to Ansible operator

### ISSUE THREAD

**Issue by t-fine** [open-horizon/examples#391]
Originally this issue was opened in the docs repo here: https://github.ibm.com/Edge-Fabric/docs/issues/629 

Instead of having an the examples operator service example being based on go, it should probably be done in either helm or ansible to make it a bit simpler. Go operators have a large controller file where the image that you're trying to deploy needs to be specified (along with any options like exposed ports) and it just seems a little unnecessarily complex. Instead if it's an sensible or helm operator we should be able to guide them thru the process from `operator-sdk new` to `tar`ing it up and deploying it with the agent 

Slack comments about this:

Glen:
How about just showing the steps needed to publish an already existing docker container? Maybe use one that need a port exposed. Kind of like the steps I show in https://github.com/TheMosquito/easy-open-horizon but for operators instead of just docker.

And maybe make a short video like this one to show it being used: https://www.youtube.com/watch?v=Fk9zJyExELU&list=PLgohd895XSUddtseFy4HxCqTqqlYfW8Ix&index=5

**Comment by mikehyde** [comment]
@t-fine Please either close this issue (if completed or no longer relevant), or change the release to `Winter` or `Future` Release.
