### ISSUE TITLE
Examples adds support for RISC-V

### ISSUE THREAD

**Issue by maiquanghiep** [open-horizon/examples#419]
Port examples for RISC-V Architecture
Examples that need to be ported:
edge/services/cpu_percent
edge/services/gps
edge/services/helloworld
edge/services/helloMMS
edge/services/nginx-operator
edge/evtstreams/cpu2evtstreams

**Comment by joewxboy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Examples adds support for RISC-V](https://trello.com/c/mWQvcEjy/5-examples-adds-support-for-risc-v)
