### ISSUE TITLE
Porting Nginx-Operator example to ppc64le

### ISSUE THREAD

**Issue by Crypt0head** [open-horizon/examples#424]
We faced the impossibility of deploying nginx-operator example on ppc64le nodes due to existing constraint in service-policy.json

**Comment by Crypt0head** [comment]
https://github.com/open-horizon/examples/pull/425

**Comment by clementkng** [comment]
@Crypt0head can this issue be closed now that #425 has been merged?

**Comment by joewxboy** [comment]
Looks like support was added to the code, but not to the Makefile?
@t-fine Is this complete and should it be closed?

**Comment by t-fine** [comment]
Oh interesting. The changes that were made in that PR allow the operator to deploy to `ppc64le` clusters but I'm curious if the service the operator deploys functions correctly...

https://github.com/open-horizon/examples/blob/049830858efe5a8233736f0971fe76588b8bbea5/edge/services/nginx-operator/ansible-role-files/deployment.j2#L20

I don't have a cluster to test that at the moment

**Comment by t-fine** [comment]
@joewxboy ^ meant to tag you

**Comment by joewxboy** [comment]
I don't know.  Do we need @cluibm to assist in the review?

**Comment by t-fine** [comment]
Ah, never mind, looks like that image is built for the `ppc64le` arch

![Screen Shot 2023-04-03 at 11 34 28 AM](https://user-images.githubusercontent.com/25443552/229597195-23f2b196-5aa1-436b-ad0b-298ea26a886c.png)
