### ISSUE TITLE
Update readmes on how to view service logs on linux

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#451]
The example readmes still say to use `sudo tail -f /var/log/syslog | grep myhelloworld[[]` on linux, but `hzn service log -f $(sudo docker ps -q --filter name=myhelloworld)` has been supported for a while now on both linux and mac.

**Comment by clementkng** [comment]
@bmpotter Just following up, do you need any assistance on this issue? I can definitely submit some PRs for this.

**Comment by bmpotter** [comment]
Troy corrected me that `hzn service log` doesn’t work with `hzn dev service start`, so closing this issue.
