### ISSUE TITLE
Remove `App.js.old` file from sdr-app/client

### ISSUE THREAD

**Issue by clementkng** [open-horizon/examples#498]
[This](https://github.com/open-horizon/examples/blob/master/cloud/sdr/ui/sdr-app/client/src/App.js.old) is a backup file and should be removed.

**Comment by Akshit42-hue** [comment]
Can I work on this issue @clementkng

**Comment by clementkng** [comment]
Hi @Akshit42-hue, I already submitted a PR (not yet merged) to fix this issue. But maybe we can join the discussion on #506 to coordinate on other work on `cloud/sdr`, or you can pick up another issue here or in the [open-horizon-services](https://github.com/open-horizon-services) organization. We're trying to migrate some examples from this repo to the open-horizon-services organization.
