### ISSUE TITLE
Need hello-world example for edge cluster

### ISSUE THREAD

**Issue by SanjeevKGupta** [open-horizon/examples#516]
Create an Hello World example for edge cluster similar to one for edge device. 

While working with a user, I came across a situation where the user was looking for a simple example (hello world example) for edge cluster and mistakenly tried to deploy the hello world edge device example without creating an operator. Yes user should have read the document and do the right things in the order specified but this is how users think and do. Current nginx-operator example is much more sophisticated and simpler example would be helpful.

**Comment by joewxboy** [comment]
@t-fine Can we get this assigned to someone?

**Comment by t-fine** [comment]
@joewxboy @SanjeevKGupta I opened an issue to track this work yesterday (also assigned to me currently) https://github.com/open-horizon/examples/issues/514 ... I've added this comment from Sanjeev and will close this duplicate issue
