### ISSUE TITLE
Feature Request: Build and test nginx-operator with v1.x operator-sdk

### ISSUE THREAD

**Issue by t-fine** [open-horizon/examples#542]
### Is your feature request related to a problem? Please describe.

The `nginx-operator` service was build with `operator-sdk v0.19.4` ... this is very outdated and should be built and tested with a newer version ... perhaps `v1.3.0` 

### Describe the solution you'd like.

Build the `nginx-operator` service with `operator-sdk v1.3.0` 

### Describe alternatives you've considered

The structure of the operator has changed dramatically after `v1.x` so perhaps there could be a script that creates the old structure from the newer operator structure if the agent experiences issues when deploying the new operator.

**Comment by johnwalicki** [comment]
Yes.  A refresh would be helpful.  The most recent operator-sdk is v1.22 - Not certain which version would be the best to support.

**Comment by t-fine** [comment]
This issue is a duplicate of https://github.com/open-horizon/examples/issues/543 ... will close this one sine there is a little more info covered in the other.
