### ISSUE TITLE
Provide operator example using latest operator-sdk 1.xx version, 

### ISSUE THREAD

**Issue by SanjeevKGupta** [open-horizon/examples#543]
### Is your feature request related to a problem? Please describe.

Current edge-cluster operator example provides example using operator-sdk version 0.17  (June 29, 2020) https://github.com/operator-framework/operator-sdk/releases?page=5 on open-horizon Operator Edge Service https://github.com/open-horizon/examples/blob/master/edge/services/nginx-operator/CreateService.md doc.   

Latest release of opeartor-sdk its 1.22. There have been 53 releases of operator-sdk since the last release of 0.17.2

Information is that examples are based on 0.19.4 but still quite old. 

- 1.xx is very different from 0.xx . A newer example will be helpful .
- Also add working example where operator deployed image is in authenticated repo in addition to docker hub.

**Comment by johnwalicki** [comment]
This anax issue will be related: https://github.com/open-horizon/anax/issues/3363

**Comment by johnwalicki** [comment]
Additional reading about writing an operator:
- https://www.magalix.com/blog/creating-custom-kubernetes-operators

**Comment by SanjeevKGupta** [comment]
@johnwalicki what's the latest on this?

**Comment by johnwalicki** [comment]
We will rebase this example when the https://github.com/open-horizon/anax/issues/3445 PR is merged.  Good progress.
