### ISSUE TITLE
nginx-operator-1.0.0 delivered with IEAM 4.3.3 does not work on an edge cluster using K3s

### ISSUE THREAD

**Issue by neurove** [open-horizon/examples#548]
**Describe the bug**
the nginx-operator (1.0.0) delivered with IEAM 4.3.3 does not work on an edge cluster using K3s.

## Version 1.0.0:

hzn agreement list
[
 {
  “name”: “Policy for edge-mgmt/shop-01 merged with edge-mgmt/policy-nginx-operator_1.0.0",
  “current_agreement_id”: “XXXXX”,
  “consumer_id”: “IBM/agbot”,
  “agreement_creation_time”: “2022-07-18 05:46:00 +0000 UTC”,
  “agreement_accepted_time”: “”,
  “agreement_finalized_time”: “”,
  “agreement_execution_start_time”: “”,
  “agreement_data_received_time”: “”,
  “agreement_protocol”: “Basic”,
  “workload_to_run”: {
   “url”: “nginx-operator”,
   “org”: “IBM”,
   “version”: “1.0.0”,
   “arch”: “amd64”
  }
 }
]

kubectl get pods -n openhorizon-agent
NAME               READY  STATUS    RESTARTS  AGE
agent-574c87d849-mzkvw      1/1   Running    0     2d14h
nginx-operator-66c468b7ff-nvhtn  0/1   Terminating  0     1s

## Version 1.0.1 from github works as expected:

hzn agreement list
[
  {
    "name": "Policy for edge-mgmt/shop-01 merged with edge-mgmt/policy-nginx-operator_1.0.1",
    "current_agreement_id": "XXXX",
    "consumer_id": "IBM/agbot",
    "agreement_creation_time": "2022-07-18 07:38:50 +0000 UTC",
    "agreement_accepted_time": "2022-07-18 07:39:00 +0000 UTC",
    "agreement_finalized_time": "2022-07-18 07:39:01 +0000 UTC",
    "agreement_execution_start_time": "2022-07-18 07:39:06 +0000 UTC",
    "agreement_data_received_time": "",
    "agreement_protocol": "Basic",
    "workload_to_run": {
      "url": "ibm.nginx-operator",
      "org": "edge-mgmt",
      "version": "1.0.1",
      "arch": "amd64"
    }
  }
]

kubectl get pods -n openhorizon-agent
NAME                             READY   STATUS    RESTARTS   AGE
agent-574c87d849-mzkvw           1/1     Running   0          2d16h
nginx-operator-f49855b98-vfhjl   1/1     Running   0          20m
nginx-677765d6b5-4gprt           1/1     Running   0          20m

**Comment by SanjeevKGupta** [comment]
Can you please update the document. Users are running into issues deploying the application.
