### ISSUE TITLE
Documentation📄: https://github.com/open-horizon/examples/blob/master/edge/evtstreams/cpu2evtstreams/PolicyRegister.md#deployment-policy

### ISSUE THREAD

**Issue by playground** [open-horizon/examples#553]
### What is the current documentation state?

Deployment Policy
Deployment Policy (sometimes called Deployment Policy) is what ties together Edge Nodes, Published...

### Where is this stated?

https://github.com/open-horizon/examples/blob/master/edge/evtstreams/cpu2evtstreams/PolicyRegister.md#deployment-policy

### Why do you want to improve the statement?

I believe that is what was used to be called

### Proposed Statement

Deployment Policy
Deployment Policy (sometimes called Business Policy) is what ties together Edge Nodes, Published

**Comment by ChandanSharma61370** [comment]
I can pick this issue

**Comment by ChandanSharma61370** [comment]
Working on this

**Comment by ChandanSharma61370** [comment]
Pull request created after doing the change
https://github.com/open-horizon/examples/pull/581

**Comment by ChandanSharma61370** [comment]
This issue is merged and can be closed

**Comment by joewxboy** [comment]
Thanks, @ChandanSharma61370 closing.
