### ISSUE TITLE
gps: aarch64/alpine docker container has been deprecated

### ISSUE THREAD

**Issue by t-fine** [open-horizon/examples#558]
**Describe the bug**
aarch64/alpine docker container has been deprecated and is causing errors when the GitHub action tried to build the `gps` service. There is also the issue of finding a `gpsd` package that can be installed by the base image.

**To Reproduce**
```
git clone https://github.com/open-horizon/examples.git
cd examples/edge/services/gps
export ARCH=arm64
make build
```

**Expected behavior**
Successful build of the `arm64` container with a `gpsd` package installed in the Dockerfile

**Additional context**

**Comment by mpeiffer** [comment]
Can I be assigned to this?

**Comment by johnwalicki** [comment]
@mpeiffer Thanks for investigating.  Remember to follow the contribution guidelines.
