### ISSUE TITLE
Add horizon bx cr doc to examples documentation

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#56]
This doc explains the steps to put a docker image (that is part of a horizon service) into the bx cr registry and use it with horizon: https://docs.google.com/document/d/1Qlff9PT_o8Qv83viKKLZda5L-o0QdRm_8Cqi7MpA1qU

Convert it to markdown, place it in `examples/edge/doc`, and link to it from the relevant other docs.

**Comment by TheMosquito** [comment]
And it is here:  https://github.com/open-horizon/examples/blob/master/edge/doc/Container-Registries.md
