### ISSUE TITLE
Feature Request: helloMMS Converge on one Dockerfile 

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/examples#564]
### Is your feature request related to a problem? Please describe.

Using the technique described in #560 and implemented in #561
The same can be done for helloMMS

Many of the examples/ repos have `Dockerfile.amd64` / `Dockerfile.arm` / `Dockerfile.arm64` / `Dockerfile.ppc64le`
I did a meld on some of these Dockerfiles and they are slightly different. (which is not good)
These multiple Dockerfiles and differences are unnecessary. We could delete them all. Create one common Dockerfile

Then in the `Makefile`, tell the docker build --platform linux/$(ARCH)
Docker/Podman will figure out which arch image to pull and build.

### Describe the solution you'd like.

Remove all the Dockerfile.* files.  Create a common `Dockerfile`

**Comment by dipesh-rawat** [comment]
@johnwalicki  Could you please assign this issue to me.
I had a go at making required changes for this issue and created a draft PR https://github.com/open-horizon/examples/pull/574 with changes. If you could please review the same and let me know if anything is missing.

**Comment by johnwalicki** [comment]
@dipesh-rawat I have assigned this issue to you

**Comment by johnwalicki** [comment]
Thanks @dipesh-rawat
