### ISSUE TITLE
Feature Request: helloSecretWorld - Converge on one Dockerfile

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/examples#565]
### Is your feature request related to a problem? Please describe.

Using the technique described in #560 and implemented in #561
The same can be done for helloSecretWorld

Many of the examples/ repos have `Dockerfile.amd64` / `Dockerfile.arm` / `Dockerfile.arm64` / `Dockerfile.ppc64le`
I did a meld on some of these Dockerfiles and they are slightly different. (which is not good)
These multiple Dockerfiles and differences are unnecessary. We could delete them all. Create one common Dockerfile

Then in the `Makefile`, tell the docker build --platform linux/$(ARCH)
Docker/Podman will figure out which arch image to pull and build.

### Describe the solution you'd like.

Remove all the Dockerfile.* files.  Create a common `Dockerfile`

**Comment by saurav1004** [comment]
@johnwalicki similar to Issue #566,  I can create a single dockerfile for the `helloSecretWorld` service too (replacing the old ones). 

If you can assign me both issues, I can write both the dockerfiles and create a common PR ?

**Comment by johnwalicki** [comment]
@saurav1004  Since this examples repo is one giant repo, you can create a single PR which modifies files in multiple example subdirectories.

Thanks for working on this issue.

**Comment by saurav1004** [comment]
@johnwalicki I have made all necessary modifications for both the services `mqttbroker` and `helloSecretWorld`. I have made a draft PR, will mark it ready for review, once you confirm

**Comment by johnwalicki** [comment]
Looks good. Nice work.  Thanks!

The PR is ready to merge once you remove the Draft status.

**Comment by saurav1004** [comment]
Thanks !! I have removed the draft status. I think you can merge now.

**Comment by johnwalicki** [comment]
This change has been released:
https://github.com/open-horizon/examples/releases/tag/v2.30.0-1142
