### ISSUE TITLE
Feature Request: mqttbroker Converge on one Dockerfile

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/examples#566]
### Is your feature request related to a problem? Please describe.

Using the technique described in #560 and implemented in #561
The same can be done for mqttbroker

Many of the examples/ repos have `Dockerfile.amd64` / `Dockerfile.arm` / `Dockerfile.arm64` / `Dockerfile.ppc64le`
I did a meld on some of these Dockerfiles and they are slightly different. (which is not good)
These multiple Dockerfiles and differences are unnecessary. We could delete them all. Create one common Dockerfile

Then in the `Makefile`, tell the docker build --platform linux/$(ARCH)
Docker/Podman will figure out which arch image to pull and build.

### Describe the solution you'd like.

Remove all the Dockerfile.* files.  Create a common `Dockerfile`

**Comment by saurav1004** [comment]
@johnwalicki I think I can work on this issue. I can create a single dockerfile for the `mqttbroker` service (replacing the old ones) the way it is done for `helloworld` [here](https://github.com/open-horizon/examples/blob/master/edge/services/helloworld/Dockerfile). Could I be assigned this issue if I got it right ?

**Comment by t-fine** [comment]
As there were no changes to the services themselves, the version does not need to be incremented, and it does not need to be built and pushed. Closing.
