### ISSUE TITLE
Add MAINTAINERS file

### ISSUE THREAD

**Issue by t-fine** [open-horizon/examples#602]
Similar to the `anax` repo we should add a MAINTAINERS file for the examples repo. Anax repo maintainers file:
https://github.com/open-horizon/anax/blob/master/MAINTAINERS.md

**Comment by marhabac33** [comment]
@t-fine I can work on this.  

Let me know if the maintainers are same as the anax repo. If not then whom to include.

**Comment by johnwalicki** [comment]
@marhabac33 - it will be a slightly different list

**Comment by marhabac33** [comment]
@johnwalicki same list plus @t-fine or need other changes.

**Comment by t-fine** [comment]
Hey @marhabac33 sorry I started a reply yesterday and something came up ... let's make it me, John, Joe, and Lily for now. Thanks!

**Comment by marhabac33** [comment]
No worries at all @t-fine. 
I have other's email addresses from anax file. Could you please share your preferred email to include?

**Comment by t-fine** [comment]
@marhabac33 oh yes! Mine is: troy.f.fine@gmail.com

**Comment by marhabac33** [comment]
@t-fine https://github.com/open-horizon/examples/pull/604 is up

**Comment by t-fine** [comment]
@marhabac33 thanks for the help!
