### ISSUE TITLE
GPS service returns non-zero elevation when using coordinates from IP address.

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/examples#68]
The http://freegeoip.net/csv/ api used by the horizon gps service was deprecated, so the ip estimated location stopped working, so i updated that code to use the new api. In the process i noticed that `get_location_from_ip_address()` doesn’t return elevation, but the gps service still returns it as `114.6` (at least for my location). From looking at the code, i couldn’t figure out how that was happening. Please debug and fix. Thx.

**Comment by TheMosquito** [comment]
I took a look at the **gps** service implementation, here:
[https://github.com/open-horizon/examples/blob/master/edge/services/gps](https://github.com/open-horizon/examples/blob/master/edge/services/gps)
I am wondering whether this is really a bug or is it a feature?  The elevation is determined using a free web service from the USGS.  This is done whenever -1.0 is passed to SetLocation (which is done when location is provided statically by the user or determined from the IP address).  Here are some code pointers:
**Starting point:**
[https://github.com/open-horizon/examples/blob/master/edge/services/gps/src/main.go#L375](https://github.com/open-horizon/examples/blob/master/edge/services/gps/src/main.go#L375)
**Code that acts when -1.0 is passed as elevation:**
[https://github.com/open-horizon/examples/blob/master/edge/services/gps/src/hgps/hgps.go#L193](https://github.com/open-horizon/examples/blob/master/edge/services/gps/src/hgps/hgps.go#L193)
**Code that invokes the USGS service:**
[https://github.com/open-horizon/examples/blob/master/edge/services/gps/src/hgps/hgps.go#L333](https://github.com/open-horizon/examples/blob/master/edge/services/gps/src/hgps/hgps.go#L333)
So I think this is the intended behavior (and it seems like a good way to handle this).  If you think it needs to change, what should the changed behavior be?

**Comment by bmpotter** [comment]
Ah, ok, i wasn't following the code carefully enough. The current code is good, so i'm closing this issue.
